set -gx config_default_loaded "true"
set -gx error_email "errors@rbmtechnologies.com"
set -gx RBM_SFTP_HOST "sftp.rbmtechnologies.com"
set -gx RABBITMQ_PORT "5672"
set -gx RABBITMQ_API_PORT "15672" set -gx RABBITMQ_API_PROTOCOL "http"
set -gx config_development_loaded "true"
set -gx vmm_db_password "gA0kniC2"
set -gx vmm_db_host "db-development.aws.rbmtechnologies.com"
set -gx RAILS_ENV "development"
set -gx host_domain "rbmtechnologies.com"
set -gx SKIP_ANCESTRY_INTEGRITY_CHECKS "true"
set -gx REDIS_URL "redis://shared-redis-lab.aws.rbmtechnologies.com:6379"
set -gx SIFT_REDIS_DB "2"
set -gx SIFT_REDIS_NAMESPACE "sift_development"
set -gx mobile_magellan_source "s3://rbm-compiled-artifacts/default/magellan/lab"
set -gx config_vmm_loaded "true"
set -gx vmm_git_comment "For vmm and job boss applications"
set -gx vmm_git_repo "git@github.com:RBM-Technologies/vmm.git"
set -gx vmm_git_branch "development"
set -gx vmm_outbound_ftp_enabled "false"
set -gx vmm_send_all_mail_to_current_user "true"
set -gx vmm_ses_key "AKIAJOP5V75B74RA5UKA"
set -gx vmm_ses_pwd "brLMdKJAGGUEYHBgA/pskjlNT++NMpFOPdWtFSha"
set -gx RAILS_ROOT "/home/app/rails/current"
set -gx JB_APPLICATION_ROOT "/home/app/rails/current"
set -gx announcements_enabled "true"
set -gx VMM_ENABLE_FILTER_AUTOCACHE_FOR_CAMPAIGN_CREATION "true"
set -gx VMM_SIFT_API_TOKEN "e6064371-c0fe-47e8-a8ba-c0394265b97a"
set -gx VMM_SIFT_DOMAIN "ec2-52-21-85-78.compute-1.amazonaws.com"
set -gx vmm_ldap_domain "ad.corp.lan"
set -gx VMM_LDAP_TREEBASE "DC ad,DC corp,DC lan"
set -gx VMM_LDAP_HOSTS "["ad4.aws.rbmtechnologies.com", "ad5.aws.rbmtechnologies.com"]"
set -gx VMM_LDAP_DOMAIN "ad.corp.lan"
set -gx ADDITIONAL_WARDEN_STRATEGIES "rbm_ldap"
set -gx ADMIN_DASHBOARD_LOCATION_MODULES "compliance_dashboard,issues,logins"
set -gx CAMPAIGN_REVIEW_ISSUES_CUSTOM_HEADERS ""
set -gx CAN_SET_FIXTURE_TYPE_ICON_PER_MERCHANdising "false"
set -gx CAN_TARGET_FIXTURE_TYPES_BY_REGION "true"
set -gx CHANGE_NAME_OF_PLANOGRAM_COPIES "false"
set -gx CONTENT_DEFAULTS_TO_IS_ORDERABLE "true"
set -gx CONTENT_LISTING_SHOW_FIXTURE_TYPE_ID "false"
set -gx DEFAULT_FROM "Merchandising Cloud <do-not-reply@rbmtechnologies.com>"
set -gx DEFAULT_TO_CURRENT_CAMPAIGN_ON_LOCATIONS_DASHBOARD "true"
set -gx DEVELOPMENT_EMAIL "development@rbmtechnologies.com"
set -gx EMAIL_TOOL_EMAIL_LOCATION_ATTRIBUTES ""
set -gx ERRORS_EMAIL "errors@rbmtechnologies.com"
set -gx FILTER_UPCOMING_CAMPAIGNS_THAT_ARE_WITHIN_X_MINUTES_OF_EACH_OTHER "0"
set -gx GET_FEEDBACK_CAMPAIGN_FROM_PLANOGRAM "false"
set -gx ISSUE_EMAIL_LOCATION_ATTRIBUTES ""
set -gx LANGUAGES "en"
set -gx LINK_CATEGORIES "STORE_RESOURCE,SMR_FEATURED,WHATS_HOT"
set -gx LOCATION_DESCRIPTION_OPERATIONS ""
set -gx MAX_FOOTPRINT "---
:memory: 16.0
:cpu: 16.0"

set -gx MAX_QUERY_RESULTS "30000"
set -gx QUESTIONNAIRE_TYPES "location, campaign, fixture"
set -gx RBM_ACTIVE_DIRECTORY_REGIONS "1"
set -gx RBM_ACTIVE_DIRECTORY_ROLE "1"
set -gx REPORT_FILENAMES_USE_BOOKMARK_NAME "true"
set -gx SEND_COMPLIANCE_REMINDERS_MUTEX "true"
set -gx SHOW_COMPLIANCE_IN_ACCORDION_ON_LOCATION_DASHBOARD "true"
set -gx SUBTEMPLATE_SCALE "1.0"
set -gx SUPPORT_EMAIL "support@rbmtechnologies.com"
set -gx LOCATION_DESCRIPTION_SEPARATOR "/"
set -gx VMM_LOGIN_FORM_STYLE "rbm_login"
set -gx vmm_use_secure_cookies "true"
set -gx RABBITMQ_OBJECTS_OF_INTEREST "Campaign,Region,Location,Category,FixtureType,Compliance,ComplianceSnapshotLog,User,Fixture,Floorplan,Feedback"
set -gx VMM_TIME_ZONE 'EST'
set -gx VMM_SHOW_COMPLIANCE_IN_ACCORDION_ON_LOCATION_DASHBOARD "true"
set -gx SITE "bby"
set -gx config_bby_loaded "true"
set -gx mobile_magellan_enabled "true"
set -gx vmm_binary_files_bucket "rbm-bby-preprod"
set -gx SIMPLE_PLANOGRAMS "false"
set -gx RABBITMQ_ENABLED "true"
set -gx BBY_EXCHANGES "zen.events"
set -gx BBY_QUEUES "vmm.bby.zen.events"
set -gx BBY_EVENTS_OF_INTEREST "update"
set -gx BBY_OBJECTS_OF_INTEREST "Feedback"
set -gx enable_compliance_visualization_dashboard "true"
set -gx VMM_EMAIL_TOOL_LOCATION_ATTRIBUTES "email"
set -gx config_bby_development_loaded "true"
set -gx RBM_SFTP_LOGIN "bby-development"
