set -gx config_default_loaded="true" # defaults.json
set -gx error_email="errors@rbmtechnologies.com" # defaults.json
set -gx RBM_SFTP_HOST="sftp.rbmtechnologies.com" # defaults.json
set -gx RABBITMQ_PORT="5672" # vmm.json
set -gx RABBITMQ_API_PORT="15672" # vmm.json
set -gx RABBITMQ_API_PROTOCOL="http" # vmm.json
set -gx config_uat_loaded="true" # uat.json
set -gx vmm_orion_domain="shared-orion-uat.aws.rbmtechnologies.com:6100" # bby-uat.json
set -gx vmm_new_relic_developer_mode="false" # uat.json
set -gx RAILS_ENV="development" # changed by load_layer_cake
set -gx host_domain="rbmtechnologies.com" # uat.json
set -gx vmm_use_secure_cookies="true" # vmm.json
set -gx vmm_db_host="bby-db-uat.aws.rbmtechnologies.com" # bby-uat.json
set -gx vmm_db_password="yOk$jU}hur" # bby-uat.json
set -gx RABBITMQ_HOST="shared-rabbitmq-uat.aws.rbmtechnologies.com" # bby-uat.json
set -gx config_vmm_loaded="true" # vmm.json
set -gx vmm_git_comment="For vmm and job boss applications" # vmm.json
set -gx vmm_git_repo="git@github.com:RBM-Technologies/vmm.git" # vmm.json
set -gx vmm_git_branch="oos_bby_v15_3_2_3_rc" # bby-uat.json
set -gx vmm_outbound_ftp_enabled="false" # vmm.json
set -gx vmm_send_all_mail_to_current_user="false" # bby-uat.json
set -gx vmm_ses_key="AKIAJOP5V75B74RA5UKA" # vmm.json
set -gx vmm_ses_pwd="brLMdKJAGGUEYHBgA/pskjlNT++NMpFOPdWtFSha" # vmm.json
set -gx RAILS_ROOT="/home/app/rails/current" # vmm.json
set -gx JB_APPLICATION_ROOT="/home/app/rails/current" # vmm.json
set -gx announcements_enabled="true" # vmm.json
set -gx VMM_ENABLE_FILTER_AUTOCACHE_FOR_CAMPAIGN_CREATION="true" # vmm.json
set -gx VMM_SIFT_API_TOKEN="e6064371-c0fe-47e8-a8ba-c0394265b97a" # vmm.json
set -gx VMM_SIFT_DOMAIN="ec2-52-21-85-78.compute-1.amazonaws.com" # vmm.json
set -gx vmm_ldap_domain="ad.corp.lan" # vmm.json
set -gx VMM_LDAP_TREEBASE="DC=ad,DC=corp,DC=lan" # vmm.json
set -gx VMM_LDAP_HOSTS="["ad4.aws.rbmtechnologies.com", "ad5.aws.rbmtechnologies.com"]" # vmm.json
set -gx VMM_LDAP_DOMAIN="ad.corp.lan" # vmm.json
set -gx ADDITIONAL_WARDEN_STRATEGIES="rbm_ldap" # vmm.json
set -gx ADMIN_DASHBOARD_LOCATION_MODULES="compliance_dashboard,issues,logins" # vmm.json
set -gx CAMPAIGN_REVIEW_ISSUES_CUSTOM_HEADERS="" # vmm.json
set -gx CAN_SET_FIXTURE_TYPE_ICON_PER_MERCHANdising="false" # vmm.json
set -gx CAN_TARGET_FIXTURE_TYPES_BY_REGION="true" # vmm.json
set -gx CHANGE_NAME_OF_PLANOGRAM_COPIES="false" # vmm.json
set -gx CONTENT_DEFAULTS_TO_IS_ORDERABLE="true" # vmm.json
set -gx CONTENT_LISTING_SHOW_FIXTURE_TYPE_ID="false" # vmm.json
set -gx DEFAULT_FROM="Merchandising Cloud <do-not-reply@rbmtechnologies.com>" # vmm.json
set -gx DEFAULT_TO_CURRENT_CAMPAIGN_ON_LOCATIONS_DASHBOARD="true" # vmm.json
set -gx DEVELOPMENT_EMAIL="development@rbmtechnologies.com" # vmm.json
set -gx EMAIL_TOOL_EMAIL_LOCATION_ATTRIBUTES="" # vmm.json
set -gx ERRORS_EMAIL="errors@rbmtechnologies.com" # vmm.json
set -gx FILTER_UPCOMING_CAMPAIGNS_THAT_ARE_WITHIN_X_MINUTES_OF_EACH_OTHER="0" # vmm.json
set -gx GET_FEEDBACK_CAMPAIGN_FROM_PLANOGRAM="false" # vmm.json
set -gx ISSUE_EMAIL_LOCATION_ATTRIBUTES="" # vmm.json
set -gx LANGUAGES="en" # vmm.json
set -gx LINK_CATEGORIES="STORE_RESOURCE,SMR_FEATURED,WHATS_HOT" # vmm.json
set -gx LOCATION_DESCRIPTION_OPERATIONS="" # vmm.json
set -gx MAX_FOOTPRINT="---
:memory: 16.0
:cpu: 16.0
" # vmm.json
set -gx MAX_QUERY_RESULTS="30000" # vmm.json
set -gx QUESTIONNAIRE_TYPES="location, campaign, fixture" # vmm.json
set -gx RBM_ACTIVE_DIRECTORY_REGIONS="1" # vmm.json
set -gx RBM_ACTIVE_DIRECTORY_ROLE="1" # vmm.json
set -gx REPORT_FILENAMES_USE_BOOKMARK_NAME="true" # vmm.json
set -gx SEND_COMPLIANCE_REMINDERS_MUTEX="true" # vmm.json
set -gx SHOW_COMPLIANCE_IN_ACCORDION_ON_LOCATION_DASHBOARD="true" # vmm.json
set -gx SUBTEMPLATE_SCALE="1.0" # vmm.json
set -gx SUPPORT_EMAIL="support@rbmtechnologies.com" # vmm.json
set -gx LOCATION_DESCRIPTION_SEPARATOR="/" # vmm.json
set -gx VMM_LOGIN_FORM_STYLE="rbm_weighted_login" # bby-uat.json
set -gx RABBITMQ_OBJECTS_OF_INTEREST="Campaign,Region,Location,Category,FixtureType,Compliance,ComplianceSnapshotLog,User,Fixture,Floorplan,Feedback" # vmm.json
set -gx VMM_TIME_ZONE="Central Time (US & Canada)" # bby.json
set -gx VMM_SHOW_COMPLIANCE_IN_ACCORDION_ON_LOCATION_DASHBOARD="true" # vmm.json
set -gx SITE="bby" # bby.json
set -gx config_bby_loaded="true" # bby.json
set -gx mobile_magellan_enabled="true" # bby.json
set -gx vmm_binary_files_bucket="rbm-bby" # bby-uat.json
set -gx SIMPLE_PLANOGRAMS="false" # bby.json
set -gx RABBITMQ_ENABLED="true" # bby.json
set -gx BBY_EXCHANGES="zen.events" # bby.json
set -gx BBY_QUEUES="vmm.bby.zen.events" # bby.json
set -gx BBY_EVENTS_OF_INTEREST="update" # bby.json
set -gx BBY_OBJECTS_OF_INTEREST="Feedback" # bby.json
set -gx enable_compliance_visualization_dashboard="true" # bby.json
set -gx VMM_EMAIL_TOOL_LOCATION_ATTRIBUTES="email" # bby.json
set -gx config_bby_uat_loaded="true" # bby-uat.json
set -gx NEW_RELIC_LICENSE_KEY="708350bdd97396299287ee794adef8fe9f77769f" # bby-uat.json
set -gx RBM_SFTP_LOGIN="bby-uat" # bby-uat.json
set -gx vmm_db_name="bby-vmm-uat" # bby-uat.json
set -gx skuter_process_count="4" # bby-uat.json
set -gx RABBITMQ_URL="amqp://bby-vmm-uat:bby-vmm-uat@shared-rabbitmq-uat.aws.rbmtechnologies.com:5672" # bby-uat.json
set -gx RABBITMQ_USER="bby-vmm-uat" # bby-uat.json
set -gx RABBITMQ_PASS="bby-vmm-uat" # bby-uat.json
set -gx vmm_orion_api_token="bby-uat-4cc750a6-c852-42d9-84a3-d4e3da45f7c5" # bby-uat.json
echo "Loaded LayerCake bby_vmm_uat.json from 2015 Dec 28 16:30"
